name: 06 - Activity Types
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop
jobs:
  echo:
    runs-on: ubunt-latest
    steps:
      - name: Mensaje
        run: echo 'Running whenever a PR is opened or synchronized AND base branch is develop'
